#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Adds the current directory to the library path
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DIR

java -cp $DIR/anchor-browser.jar:$DIR/anchor-launcher.jar:$DIR/../lib/* -Xms500m -Xmx2000m org.anchoranalysis.browser.launcher.LaunchInteractiveBrowser "$@"

