on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  build:
    uses: anchoranalysis/anchor-java-cicd/.github/workflows/push_master.yml@main
    secrets: inherit
    with:
       upload-artifact: target/anchor-*-anchor.zip
